# Workflow syntax:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: cpp-linter

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:

jobs:
  cpp-linter:
    strategy:
      matrix:
        compiler: [clang]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run cmake to generate compilation database
        run: cmake -S . -B . -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=1
      - uses: cpp-linter/cpp-linter-action@v1
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          lines-changed-only: true
          tidy-checks: >-
            boost-*
            ,bugprone-*
            ,performance-*
            ,readability-*
            ,portability-*
            ,modernize-*
            ,clang-analyzer-*
            ,cppcoreguidelines-*
            ,-cppcoreguidelines-avoid-magic-numbers
            ,-readability-magic-numbers

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
